# SPDX-FileCopyrightText: 2024 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name = "examples"
description = "Curve_Fit examples"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["examples"]

[configuration]
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"
"*".ada_version = "Ada2022"

[build-profiles]
curve_fit = "development"

[[depends-on]]
curve_fit = "*"

[[pins]]
curve_fit = { path='..' }

